name: 'Conventional Commits Versioning'
description: 'Provide a description here'
author: 'Brad'

# Define your inputs here.
inputs:
  token:
    description: GitHub Token
    required: true
  branch:
    description: The branch to fetch commit history from
    required: false
    default: main
  prefix:
    description: The prefix to use for the tag
    required: false
    default: v

# Define your outputs here.
outputs:
  old:
    description: The old version
  new:
    description: The new version

runs:
  using: node16
  main: dist/index.js

branding:
  icon: activity
  color: blue
